#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/loveconnect?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: dltmdduq12
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update  # 개발 중엔 update / 운영 땐 validate or none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
aligo:
  api:
    key: 43yybnsb3bbcpczvdj5mk2dyhd8xxo96
    user_id: tmdduqflfl
    sender: 01033457392  # ⚠️ 반드시 알리고에 등록된 발신번호 사용!
    url: https://apis.aligo.in/send/
