version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: loveconnect-redis
    ports:
      - "6379:6379"
    networks:
      - loveconnect-net

  app:
    image: ${DOCKERHUB_USERNAME}/loveconnect:latest
    container_name: loveconnect-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - loveconnect-net
    # === 외부 파일을 컨테이너 안으로 연결 ===
    volumes:
      - ./src/main/resources:/app/resources
    environment:
      - SPRING_PROFILES_ACTIVE=default
      # 파일을 직접 참조하도록 경로 수정
      - TOSS_CERT_PATH=file:/app/resources/toss-cert.p12
      - TOSS_CERT_PASSWORD=199310
      - TOSS_DECRYPT_KEY=JH1l/ziZ8/f50lfmgitC0fMHgdiqh6UZ65hjTrR7Kds=
      - TOSS_DECRYPT_AAD=TOSS
      - TOSS_API_BASE_URL=https://apps-in-toss-api.toss.im

networks:
  loveconnect-net:
