version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: loveconnect-redis
    ports:
      - "6379:6379"
    networks:
      - loveconnect-net

  app:
    image: leeseungyeop/loveconnect:latest  # 이미지 직접 사용
    container_name: loveconnect-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - loveconnect-net

networks:
  loveconnect-net:
