version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: loveconnect-db
    environment:
      MYSQL_DATABASE: loveconnect
      MYSQL_ROOT_PASSWORD: dltmdduq12
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - loveconnect-net

  redis:
    image: redis:7.2
    container_name: loveconnect-redis
    ports:
      - "6379:6379"
    networks:
      - loveconnect-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loveconnect-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - loveconnect-net

volumes:
  db_data:

networks:
  loveconnect-net:
