version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: loveconnect-redis
    ports:
      - "6379:6379"
    networks:
      - loveconnect-net

  app:
    image: leeseungyeop/loveconnect:latest
    container_name: loveconnect-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - loveconnect-net

    volumes:
      - ./src/main/resources/toss-cert.p12:/app/certs/toss-cert.p12

    environment:
      - SPRING_PROFILES_ACTIVE=toss

      # π”¥ mTLS ν•„μ
      - TOSS_CERT_PATH=file:/app/certs/toss-cert.p12
      - TOSS_CERT_PASSWORD=199310   # β† π”¥ λ°λ“μ‹ μ¶”κ°€

      # π”¥ λ³µνΈν™” ν•„μ
      - TOSS_DECRYPT_KEY=JH1l/ziZ8/f50lfmgitC0fMHgdiqh6UZ65hjTrR7Kds=
      - TOSS_DECRYPT_AAD=TOSS

      - TOSS_API_BASE_URL=https://apps-in-toss-api.toss.im

networks:
  loveconnect-net:
